---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/chris-moreton/concourse-pipeline-controller.git
    branch: master
    password: ((GITHUB_API_TOKEN))
    private_key: ((GITHUB_DEPLOY_KEY.private_key))
- name: trigger-interval
  type: time
  source: {interval: 60m}
jobs:
- name: init-pipelines
  public: false
  plan:
  - get: trigger-interval
    trigger: true
  - get: source-code
  - task: init-pipelines
    file: source-code/devops/concourse/tasks/init-pipelines.yml
    params:
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      CONCOURSE_HOST: ((CONCOURSE_HOST))
      CONCOURSE_ADMIN_PASSWORD: ((CONCOURSE_ADMIN_PASSWORD))
