---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:chris-moreton/concourse-pipeline-initialiser
    branch: a-better-way
    private_key: ((GITHUB_DEPLOY_KEY.private_key))
    password: ((GITHUB_API_TOKEN))
- name: trigger-interval
  type: time
  source: {interval: 1m}
- name: directorzone-api
  type: git
  source:
    uri: git@github.com:chris-moreton/directorzone-api
    branch: master
    private_key: ((directorzone-api/GITHUB_DEPLOY_KEY.private_key))
    password: ((GITHUB_API_TOKEN))
- name: directorzone-frontend
  type: git
  source:
    uri: git@github.com:chris-moreton/directorzone-frontend
    branch: master
    private_key: ((directorzone-frontend/GITHUB_DEPLOY_KEY.private_key))
    password: ((GITHUB_API_TOKEN))
- name: tennisform-odds-widget
  type: git
  source:
    uri: git@github.com:chris-moreton/tennisform-odds-widget
    branch: master
    private_key: ((tennisform-odds-widget/GITHUB_DEPLOY_KEY.private_key))
    password: ((GITHUB_API_TOKEN))
- name: tennisform-vue-widget
  type: git
  source:
    uri: git@github.com:chris-moreton/tennisform-vue-widget
    branch: master
    private_key: ((tennisform-vue-widget/GITHUB_DEPLOY_KEY.private_key))
    password: ((GITHUB_API_TOKEN))
jobs:
- name: directorzone-api
  public: false
  plan:
  - get: trigger-interval
    trigger: true
  - get: directorzone-api
    trigger: false
  - get: source-code
    trigger: false
  - task: init-pipelines
    params:
      PROJECT: directorzone-api
      CONCOURSE_ADMIN_PASSWORD: ((CONCOURSE_ADMIN_PASSWORD))
    file: source-code/devops/concourse/tasks/init-pipeline.yml
- name: directorzone-frontend
  public: false
  plan:
  - get: trigger-interval
    trigger: true
  - get: directorzone-frontend
    trigger: false
  - get: source-code
    trigger: false
  - task: init-pipelines
    params:
      PROJECT: directorzone-frontend
      CONCOURSE_ADMIN_PASSWORD: ((CONCOURSE_ADMIN_PASSWORD))
    file: source-code/devops/concourse/tasks/init-pipeline.yml
- name: tennisform-odds-widget
  public: false
  plan:
  - get: trigger-interval
    trigger: true
  - get: tennisform-odds-widget
    trigger: false
  - get: source-code
    trigger: false
  - task: init-pipelines
    params:
      PROJECT: tennisform-odds-widget
      CONCOURSE_ADMIN_PASSWORD: ((CONCOURSE_ADMIN_PASSWORD))
    file: source-code/devops/concourse/tasks/init-pipeline.yml
- name: tennisform-vue-widget
  public: false
  plan:
  - get: trigger-interval
    trigger: true
  - get: tennisform-vue-widget
    trigger: false
  - get: source-code
    trigger: false
  - task: init-pipelines
    params:
      PROJECT: tennisform-vue-widget
      CONCOURSE_ADMIN_PASSWORD: ((CONCOURSE_ADMIN_PASSWORD))
    file: source-code/devops/concourse/tasks/init-pipeline.yml