---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:chris-moreton/concourse-pipeline-initialiser
    branch: master
    private_key: ((GITHUB_DEPLOY_KEY.private_key))
    password: ((NETSENSIA_GITHUB_API_TOKEN))
- name: trigger-interval
  type: time
  source: {interval: 5m}
jobs:
- name: init-pipelines
  public: false
  plan:
  - get: trigger-interval
    trigger: true
  - get: source-code
  - task: init-pipelines
    file: source-code/devops/concourse/tasks/init-pipelines.yml
    params:
      AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      CONCOURSE_NETSENSIA_PASSWORD: ((CONCOURSE_NETSENSIA_PASSWORD))
