FROM ubuntu:xenial
MAINTAINER "Chris Moreton <chris@netsensia.com>"

RUN apt-get update && apt-get install -y wget unzip curl python3.6 python-pip
RUN pip install pyyaml boto3 gitpython
RUN pip install --upgrade pip