FROM ubuntu:xenial
MAINTAINER "Chris Moreton <chris@netsensia.com>"

RUN apt-get update
RUN apt-get -y install wget unzip curl python python-pip git-core
RUN wget https://github.com/EngineerBetter/control-tower/releases/download/0.4.0/control-tower-linux-amd64
RUN chmod +x control-tower-linux-amd64
RUN mv control-tower-linux-amd64 /usr/local/bin/control-tower
RUN wget https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/2.4.0/credhub-linux-2.4.0.tgz
RUN tar -zxvf credhub-linux-2.4.0.tgz
RUN mv credhub /usr/local/bin
RUN pip install pyyaml
RUN pip install --upgrade pip
RUN wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
RUN unzip terraform_0.11.13_linux_amd64.zip
RUN mv terraform /usr/local/bin/
RUN bash -c "$(curl -fsSL https://raw.github.com/orange-cloudfoundry/terraform-provider-credhub/master/bin/install.sh)"
RUN mkdir -p ~/.terraform.d/plugins/linux_amd64
RUN wget -O ~/.terraform.d/plugins/linux_amd64/terraform-provider-cloudfoundry https://github.com/mevansam/terraform-provider-cf/releases/download/0.9.9/terraform-provider-cf_linux_amd64
RUN chmod +x ~/.terraform.d/plugins/linux_amd64/terraform-provider-cloudfoundry
