FROM ubuntu:xenial
MAINTAINER "Chris Moreton <chris@netsensia.com>"

RUN apt-get update -y
RUN apt-get install -y software-properties-common
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
RUN apt-get update -y
RUN apt-get install -y php7.3
RUN apt-get install -y curl apt-transport-https npm
RUN npm install -g n
RUN n 10
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get -y update
RUN apt-get install -y yarn
RUN curl -s https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN apt-get -y install libpng-dev
RUN apt-get install -y php7.3-dom php7.3-mbstring php7.3-gd
