platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: source-code
outputs:
  - name: build
run:
  dir: source-code
  path: sh
  args:
    - -exc
    - |
      ./gradlew build
      cp build/libs/((PRODUCT))-((COMPONENT)).jar ../build/((PRODUCT))-((COMPONENT)).jar
caches:
  - path: .gradle/
  - path: .m2/
