outputs:
  - name: images
platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.5
inputs:
- name: source-code
run:
  path: sh
  dir: source-code
  args:
    - -ec
    - |
      echo "Logging into Concourse..."
      fly --target netsensia-concourse login --insecure --concourse-url https://concourse.netsensia.com -u admin -p $CONCOURSE_ADMIN_PASSWORD
      echo "Syncing..."
      fly --target netsensia-concourse sync
      echo "Hello"
      pwd
      python3 source-code/devops/concourse/tasks/bin/init-pipeline.py $PROJECT .
