outputs:
  - name: images
platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia
    tag: python27
run:
  path: sh
  args:
    - -exc
    - |
      pip install pyyaml
      apt-get update && apt-get -y install openssh-client
      cd devops/tasks/bin
      python init-pipelines.py repositories.yml
