outputs:
  - name: images
platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.5
inputs:
  - name: source-code
run:
  path: sh
  dir: source-code
  args:
    - -exc
    - |
      cd devops/concourse/tasks/bin
      python3 init-pipelines.py
