outputs:
  - name: images
platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.3
inputs:
  - name: source-code
run:
  path: sh
  dir: source-code
  args:
    - -exc
    - |
      cd devops/concourse/tasks/bin
      echo "python init-pipelines.py ../../../../repositories.yml $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $CONCOURSE_NETSENSIA_PASSWORD"
      python init-pipelines.py ../../../../repositories.yml $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $CONCOURSE_NETSENSIA_PASSWORD
