#-------------------------------------------------------------------------------------------------
# Example usage:
#-------------------------------------------------------------------------------------------------
#- name: build
#  public: false
#  plan:
#  - get: source-code
#    trigger: false
#  - get: pipeline-controller
#    trigger: false
#  - task: build
#    file: pipeline-controller/devops/concourse/tasks/external/build-gradle.yml
#  - put: packaged-build
#    params:
#      file: build/((PRODUCT))-((COMPONENT)).jar
#-------------------------------------------------------------------------------------------------



platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: source-code
outputs:
  - name: build
run:
  dir: source-code
  path: sh
  args:
    - -exc
    - |
      ./gradlew build
      cp build/libs/((PRODUCT))-((COMPONENT)).jar ../build/((PRODUCT))-((COMPONENT)).jar
caches:
  - path: .gradle/
  - path: .m2/
