platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.7
inputs:
  - name: source-code
outputs:
  - name: build
run:
  dir: source-code
  path: sh
  args:
    - -exc
    - |
      n 10.14
      npm install
      FILENAME=((PRODUCT))-((COMPONENT)).tar.gz
      tar -zcf $FILENAME
      cp build/libs/$FILENAME ../build/$FILENAME
caches:
  - path: .gradle/
  - path: .m2/
