platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: source-code
outputs:
  - name: build
run:
  dir: source-code
  path: sh
  args:
    - -exc
    - |
      ./gradlew build
      JAR_FILE=((PRODUCT))-((COMPONENT)).jar
      ZIP_FILE=((PRODUCT))-((COMPONENT)).tar.gz
      cd build/libs
      tar -zcvf $ZIP_FILE $JAR_FILE
      cp $ZIP_FILE ../../../build/$ZIP_FILE
caches:
  - path: .gradle/
  - path: .m2/
