platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: source-code
outputs:
  - name: build
run:
  dir: source-code
  path: sh
  args:
    - -exc
    - |
      npm install
      FILENAME=((PRODUCT))-((COMPONENT)).tar.gz
      tar -zcvf $FILENAME .
      cp build/libs/$FILENAME ../build/$FILENAME
caches:
  - path: .gradle/
  - path: .m2/
