platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/php
    tag: 1.0.2
inputs:
  - name: source-code
outputs:
  - name: build
run:
  dir: source-code
  path: sh
  args:
    - -exc
    - |
      yarn install
      composer install
      FILENAME=((PRODUCT))-((COMPONENT)).tar.gz
      tar -zcf $FILENAME . || true
      cp $FILENAME ../build/$FILENAME
