#-------------------------------------------------------------------------------------------------
# Example usage:
#-------------------------------------------------------------------------------------------------
#- name: build-infrastructure-aat
#  public: false
#  plan:
#    - get: source-code
#      passed:
#        - build
#      trigger: true
#    - get: pipeline-controller
#      trigger: false
#    - task: call-terraform
#      file: pipeline-controller/devops/concourse/tasks/external/build-infrastructure.yml
#      vars:
#        ENVIRONMENT: aat
#-------------------------------------------------------------------------------------------------

platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/terraform
    version: latest
inputs:
  - name: pipeline-controller
  - name: source-code
run:
  path: sh
  dir: pipeline-controller/devops/terraform/product
  args:
    - -exc
    - |
      cat > backend.config << EOL
      access_key="((pipeline-controller/AWS_ACCESS_KEY_ID))"
      secret_key="((pipeline-controller/AWS_SECRET_ACCESS_KEY))"
      key="((PRODUCT))-((ENVIRONMENT)).tfstate"
      bucket="((pipeline-controller/STATE_BUCKET))"
      EOL
      terraform init -backend-config=./backend.config
      terraform plan \
        -var='credhub_host=((pipeline-controller/CONCOURSE_HOST))' \
        -var='credhub_client_id=((pipeline-controller/CREDHUB_CLIENT))' \
        -var='credhub_client_secret=((pipeline-controller/CREDHUB_SECRET))' \
        -var='environment=((ENVIRONMENT))' \
        -var='product=((PRODUCT))' \
        -var='component=((COMPONENT))'
      terraform apply \
        -auto-approve \
        -var='credhub_host=((pipeline-controller/CONCOURSE_HOST))' \
        -var='credhub_client_id=((pipeline-controller/CREDHUB_CLIENT))' \
        -var='credhub_client_secret=((pipeline-controller/CREDHUB_SECRET))' \
        -var='environment=((ENVIRONMENT))' \
        -var='product=((PRODUCT))' \
        -var='component=((COMPONENT))'
      cd ../component
      cp ../../../source-code/devops/terraform/custom-* .
      cat > backend.config << EOL
      access_key="((pipeline-controller/AWS_ACCESS_KEY_ID))"
      secret_key="((pipeline-controller/AWS_SECRET_ACCESS_KEY))"
      key="((PRODUCT))-((COMPONENT))-((ENVIRONMENT)).tfstate"
      bucket="((pipeline-controller/STATE_BUCKET))"
      EOL
      terraform init -backend-config=./backend.config
      terraform plan \
        -var='credhub_host=((pipeline-controller/CONCOURSE_HOST))' \
        -var='credhub_client_id=((pipeline-controller/CREDHUB_CLIENT))' \
        -var='credhub_client_secret=((pipeline-controller/CREDHUB_SECRET))' \
        -var='environment=((ENVIRONMENT))' \
        -var='product=((PRODUCT))' \
        -var='component=((COMPONENT))'
      terraform apply \
        -auto-approve \
        -var='credhub_host=((pipeline-controller/CONCOURSE_HOST))' \
        -var='credhub_client_id=((pipeline-controller/CREDHUB_CLIENT))' \
        -var='credhub_client_secret=((pipeline-controller/CREDHUB_SECRET))' \
        -var='environment=((ENVIRONMENT))' \
        -var='product=((PRODUCT))' \
        -var='component=((COMPONENT))'
