platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
outputs:
  - name: manifests
run:
  path: sh
  dir: manifests
  args:
    - -exc
    - |
      cat > manifest.yaml << EOT
      ---
      applications:
      - name: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
        buildpack: nodejs_buildpack
        memory: 768M
        command: npm run start
      env:
        NODE_ENV: production
        AUTH0_DOMAIN: dzone.auth0.com
        BASE_URL: https://((PRODUCT))-((COMPONENT))-((ENVIRONMENT)).cfapps.io
      EOT


      if [ "((ENVIRONMENT))" == "prod" ]
      then

      cat >> manifest.yaml << EOT
        AUTH0_CLIENT_ID: ((prod/AUTH0_CLIENT_ID))
        API_URL: ((prod/API_URL))
      EOT
      else
      cat >> manifest.yaml << EOT
        AUTH0_CLIENT_ID: ((aat/AUTH0_CLIENT_ID))
        API_URL: ((aat/API_URL))
      EOT
      fi


