platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.8
outputs:
  - name: manifests
run:
  path: bash
  dir: manifests
  args:
    - -exc
    - |
      cat > manifest.yml << EOT
      ---
      applications:
      - name: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
        buildpack: nodejs_buildpack
        memory: 1G
        command: npm run start
      env:
        NODE_ENV: production
      EOT
      export AWS_ACCESS_KEY_ID=((pipeline-controller/AWS_ACCESS_KEY_ID))
      export AWS_SECRET_ACCESS_KEY=((pipeline-controller/AWS_SECRET_ACCESS_KEY))
      echo "Logging into Concourse..."
      fly --target netsensia-concourse login --insecure --concourse-url https://((pipeline-controller/CONCOURSE_HOST)) -u admin -p ((pipeline-controller/CONCOURSE_ADMIN_PASSWORD))
      echo "Syncing..."
      fly --target netsensia-concourse sync
      echo "Logging into CredHub..."
      eval "$(control-tower info --iaas aws --env --region eu-west-2 netsensia-concourse)"
      ENV=((ENVIRONMENT))
      OUTPUT=`credhub find -n concourse/main/((PRODUCT))-((COMPONENT))/$ENV/env`
      ENV_VARS=$(echo $OUTPUT | grep -o "((ENVIRONMENT))/\S*")
      while IFS=' ' read -ra VAL; do
            for i in "${VAL[@]}"; do
                VALUE=`credhub get -q -n concourse/main/((PRODUCT))-((COMPONENT))/$i`
                ENV_VAR=${i/$ENV\/env\//}
      cat >> manifest.yml << EOT
        $ENV_VAR: $VALUE
      EOT
            done
      done <<< "$ENV_VARS"

