platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
outputs:
  - name: manifests
run:
  path: sh
  dir: manifests
  args:
    - -exc
    - |
      if [ "((ENVIRONMENT))" == "prod" ]
      then
        INSTANCES=1
      else
        INSTANCES=1
      fi
      cat > manifest.yaml << EOT
      ---
      applications:
      - name: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
        buildpack: nodejs_buildpack
        memory: 768M
        instances: $INSTANCES
        services:
          - ((COMPONENT))-mysql
          - ((COMPONENT))-elasticsearch
        env:
          SPRING_PROFILES_ACTIVE: production
      EOT
      if [ "((ENVIRONMENT))" == "prod" ]
      then
          cat >> manifest.yaml << EOT
      EOT
      else
          cat >> manifest.yaml << EOT
      EOT
      fi


