platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
outputs:
  - name: manifests
run:
  path: sh
  dir: manifests
  args:
    - -exc
    - |
      cat > manifest.yaml << EOT
      ---
      applications:
      - name: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
        buildpack: nodejs_buildpack
        memory: 768M
        command: npm run start
      env:
        NODE_ENV: production
      EOT



