platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
outputs:
  - name: manifests
run:
  path: sh
  dir: manifests
  args:
    - -exc
    - |
      cat > manifest.yaml << EOT
      ---
      applications:
      - name: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
        buildpack: nodejs_buildpack
        memory: 768M
      EOT
      if [ "((ENVIRONMENT))" == "prod" ]
      then
          cat >> manifest.yaml << EOT
          NODE_ENV: production
          AUTH0_DOMAIN: dzone.auth0.com
          AUTH0_CLIENT_ID: ((prod/AUTH0_CLIENT_ID))
          BASE_URL: https://((PRODUCT))-((COMPONENT))-prod.cfapps.io
      EOT
      else
          cat >> manifest.yaml << EOT
          NODE_ENV: production
          AUTH0_DOMAIN: dzone.auth0.com
          AUTH0_CLIENT_ID: ((aat/AUTH0_CLIENT_ID))
          BASE_URL: https://((PRODUCT))-((COMPONENT))-aat.cfapps.io
      EOT
      fi


