platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.12
inputs:
  - name: packaged-build
  - name: manifests
  - name: source-code
params:
  CF_USER: ((CLOUD_FOUNDRY_DEPLOY_USER.username))
  CF_PASS: ((CLOUD_FOUNDRY_DEPLOY_USER.password))
  CF_SPACE: ((PRODUCT))-((ENVIRONMENT))
  CF_APP: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
  TEST_URL: https://((PRODUCT))-((COMPONENT))-((ENVIRONMENT)).cfapps.io
run:
  path: bash
  dir: packaged-build
  args:
    - -exc
    - |
      ZIP_FILE=((PRODUCT))-((COMPONENT)).tar.gz
      tar -zxf $ZIP_FILE
      rm $ZIP_FILE
      cf login -a api.run.pivotal.io -u $CF_USER -p $CF_PASS -s $CF_SPACE
      cp ../manifests/manifest.yml .
      cat manifest.yml
      SMOKE_TEST=../source-code/smoketest/smoketest.sh
      if test -f $SMOKE_TEST; then
         SMOKE_SWITCH="--smoke-test $SMOKE_TEST"
      else
         SMOKE_SWITCH=""
      fi
      export CF_TRACE=~/cf-trace.log
      cf blue-green-deploy $CF_APP --delete-old-apps $SMOKE_SWITCH