platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
inputs:
  - name: packaged-build
  - name: manifests
params:
  CF_USER: ((pipeline-controller/CLOUD_FOUNDRY_DEPLOY_USER.username))
  CF_PASS: ((pipeline-controller/CLOUD_FOUNDRY_DEPLOY_USER.password))
  CF_SPACE: ((PRODUCT))-((ENVIRONMENT))
  CF_APP: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
run:
  path: sh
  dir: packaged-build
  args:
    - -exc
    - |
      ZIP_FILE=((PRODUCT))-((COMPONENT)).tar.gz
      tar -zxf $ZIP_FILE
      rm $ZIP_FILE
      cat > .cfignore << EOT
      node_modules/.cache
      EOT
      INDEX=`find .next/server/static -name index.js`;
      if [ ! -z $INDEX ];
      then
        if [ "prod" == "prod" ];
        then
          API_URL=((prod/API_URL))
        else
          API_URL=((aat/API_URL))
        fi
        API_URL=${API_URL//\//\\\/}
        API_URL=${API_URL//\./\\\.}
        sed -i -e 's/API_URL: undefined/API_URL: $API_URL/g' $INDEX
      fi
      cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
      cf install-plugin blue-green-deploy -f -r CF-Community
      cf login -a api.run.pivotal.io -u $CF_USER -p $CF_PASS -s $CF_SPACE
      cp ../manifests/manifest.yaml .
      export CF_TRACE=~/cf-trace.log
      cf blue-green-deploy $CF_APP
