platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.10
inputs:
  - name: packaged-build
  - name: manifests
  - name: source-code
params:
  CF_USER: ((CLOUD_FOUNDRY_DEPLOY_USER.username))
  CF_PASS: ((CLOUD_FOUNDRY_DEPLOY_USER.password))
  CF_SPACE: ((PRODUCT))-((ENVIRONMENT))
  CF_APP: ((PRODUCT))-((COMPONENT))-((ENVIRONMENT))
run:
  path: bash
  dir: packaged-build
  args:
    - -exc
    - |
      ZIP_FILE=((PRODUCT))-((COMPONENT)).tar.gz
      tar -zxf $ZIP_FILE
      rm $ZIP_FILE
      cat > .cfignore << EOT
      node_modules/.cache
      EOT
      cf login -a api.run.pivotal.io -u $CF_USER -p $CF_PASS -s $CF_SPACE
      cp ../manifests/manifest.yml .
      cat manifest.yml
      cf blue-green-deploy $CF_APP --delete-old-apps $SMOKE_SWITCH

