#-------------------------------------------------------------------------------------------------
# Example usage:
#-------------------------------------------------------------------------------------------------
#- name: backup-database
#  public: false
#  plan:
#    - get: source-code
#      passed:
#        - build-infrastructure-prod
#      trigger: false
#    - get: pipeline-controller
#      trigger: false
#    - task: dump-data
#      file: pipeline-controller/devops/concourse/tasks/external/dump-mysql-data.yml
#      params:
#        DB_HOST: ((prod/DB_HOST))
#        DB_NAME: ((prod/DB_NAME))
#        DB_USER: ((prod/DB_USER.username))
#        DB_PASS: ((prod/DB_USER.password))
#      vars:
#        ENVIRONMENT: prod
#    - put: data-dump
#      params:
#        file: data-dump/((SQL_DUMP_FILENAME)).tar.gz
#-------------------------------------------------------------------------------------------------

platform: linux
image_resource:
  type: docker-image
  source:
    repository: mysql
    tag: 5.6.42
outputs:
  - name: data-dump
run:
  dir: data-dump
  path: sh
  args:
    - -exc
    - |
      mysqldump -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME > ((SQL_DUMP_FILENAME))
      tar -zcvf ((SQL_DUMP_FILENAME)).tar.gz ((SQL_DUMP_FILENAME))
