platform: linux
image_resource:
  type: docker-image
  source:
    repository: netsensia/pipelinefull
    tag: 1.0.8
run:
  path: sh
  dir: packaged-build
  args:
    - -exc
    - |
      echo "Hello, I am a placeholder for a functional test suite"