platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial
outputs:
  - name: dump-dir
run:
  dir: dump-dir
  path: sh
  args:
    - -exc
    - |
      apt-get update && apt-get -y install openssh-client
      echo $SERVER_KEY | sed -e 's/\(KEY-----\)\s/\1\n/g; s/\s\(-----END\)/\n\1/g' | sed -e '2s/\s\+/\n/g' > server_key
      chmod 600 server_key
      ssh -o StrictHostKeyChecking=no -i server_key forge@www.director-zone.com "MYSQL_PWD=$LEGACY_DB_PASS mysqldump -u$LEGACY_DB_USER $LEGACY_DB_NAME --ignore-table=directorzone_old.marketplace" > ((legacy/SQL_DUMP_FILENAME))
      tar -zcvf ((legacy/SQL_DUMP_FILENAME)).tar.gz ((legacy/SQL_DUMP_FILENAME))