#-------------------------------------------------------------------------------------------------
# Example usage:
#-------------------------------------------------------------------------------------------------
#- name: load-database-aat
#  public: false
#  plan:
#    - get: source-code
#      passed:
#        - build-infrastructure-aat
#      trigger: true
#    - get: data-dump
#      trigger: false
#    - task: load-data
#      file: pipeline-controller/devops/concourse/tasks/external/load-mysql-data.yml
#      params:
#        DB_HOST: ((aat/DB_HOST))
#        DB_NAME: ((aat/DB_NAME))
#        DB_USER: ((aat/DB_USER.username))
#        DB_PASS: ((aat/DB_USER.password))
#-------------------------------------------------------------------------------------------------

platform: linux
image_resource:
  type: docker-image
  source:
    repository: mysql
    tag: 5.6.42
inputs:
  - name: data-dump
run:
  dir: data-dump
  path: sh
  args:
    - -exc
    - |
      tar -zxvf ../data-dump/((SQL_DUMP_FILENAME)).tar.gz
      mysql -h$DB_HOST -u$DB_USER -p$DB_PASS --execute "DROP DATABASE IF EXISTS $DB_NAME;"
      mysql -h$DB_HOST -u$DB_USER -p$DB_PASS --execute "CREATE DATABASE $DB_NAME;"
      mysql -h$DB_HOST -u$DB_USER $DB_NAME -p$DB_PASS --execute "SET FOREIGN_KEY_CHECKS=0;"
      mysql -h$DB_HOST -u$DB_USER $DB_NAME -p$DB_PASS --execute "source ((SQL_DUMP_FILENAME))"
      mysql -h$DB_HOST -u$DB_USER $DB_NAME -p$DB_PASS --execute "SET FOREIGN_KEY_CHECKS=1;"