---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:chris-moreton/concourse-pipeline-initialiser
    branch: master
    private_key: ((pipeline-initialiser/GITHUB_DEPLOY_KEY.private_key))
    password: ((NETSENSIA_GITHUB_API_TOKEN))

- name: resource-app
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: source-code
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: source-code/devops/tasks/init-pipelines.yml
